name: CWMarket
main: com.clashwars.cwmarket.bukkit.CWMarketPlugin
version: '2.0'
author: ClashWars
description: ClashWars Market plugin
depend: [Vault]
commands:
  market:
    description: Main command
    usage: /<command>
    aliases: [ma, shop]