main : com.clashwars.cwmarket.CWMarket
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
depend: [Vault]
commands:
  market:
    description: Main command
    usage: /<command>
    aliases: [ma, shop]